# Generated by Django 4.2.14 on 2024-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_follow_owner_remove_follow_target_and_more"),
        ("catalog", "0001_initial_0_10"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="verified_creators",
            field=models.ManyToManyField(
                related_name="verified_works", to="users.apidentity"
            ),
        ),
    ]
