name: tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  django:
    runs-on: ubuntu-latest
    env:
      NEODB_DB_USER: neodb
      NEODB_DB_PASSWORD: aubergine
      NEODB_DB_NAME: neodb
      NEODB_DB_PORT: 5432
      NEODB_REDIS_PORT: 6379
      TAKAHE_DB_NAME: takahe
      TAKAHE_DB_USER: takahe
      TAKAHE_DB_PASSWORD: aubergine
      TAKAHE_DB_PORT: 5432

    services:
      redis:
        image: redis
        ports:
          - ${{ env.NEODB_REDIS_PORT }}:6379
      db:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.NEODB_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.NEODB_DB_PASSWORD }}
          POSTGRES_DB: ${{ env.NEODB_DB_NAME }}
        ports:
          - ${{ env.NEODB_DB_PORT }}:5432
      db2:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.TAKAHE_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.TAKAHE_DB_PASSWORD }}
          POSTGRES_DB: ${{ env.TAKAHE_DB_NAME }}
        ports:
          - ${{ env.TAKAHE_DB_PORT }}:5432
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
